### ISSUE TITLE
Cached parameters

### ISSUE THREAD

**Issue by smurfix** [Dorthu/openapi3#110]
Consider this code:

```
async with OpenAPI(server_oapi3_data) as api:
    while True:
        res=await api.call_foo(parameters=dict(bar="baz",page_size=100))
        while True:
            for r in res.data:
                ... # whatever(r)
            npt=res.next_page_token
            if not npt:
                break
            res=await api.call_foo(parameters=dict(bar="baz",next_page_token=npt,page_size=100))
```

This fails because the value of `next_page_token` gets cached. I have to explicitly pass `next_page_token=None` in the first call.

I consider this to be a bug. What if somewhere entirely else in my codebase I add a call with `obscure_filter=some_value`? Do I now add `obscure_filter=None` to each of these? and what happens if the server reacts differently based on whether that filter is not present vs. empty?

**Comment by commonism** [comment]
[async/await?](https://github.com/search?q=repo%3ADorthu%2Fopenapi3%20async&type=code) - I'm interested in an MRE.

The request is stored in the Operation.
https://github.com/Dorthu/openapi3/blob/e6cbc94ebf5179df75d980848900d73b5378be4c/openapi3/paths.py#L191
Re-set for each call.
https://github.com/Dorthu/openapi3/blob/e6cbc94ebf5179df75d980848900d73b5378be4c/openapi3/paths.py#L310

Using threads?

**Comment by smurfix** [comment]
No, not multithreaded. The above code basically is the MRE, nothing else is happening.

I'll have to dig further where exactly that parameter is stored.

**Comment by commonism** [comment]
OpenAPI() is not an async context manager

```
>       async with openapi3.OpenAPI(data) as client:
E       AttributeError: __aenter__
```

and the call_ interface is not awaitable.

This can't be working code using this library.
Trying to to MRE this:
https://gist.github.com/commonism/2ea36e85b29bcfa4a53a7326b584989b

asyncio.to_thread is used to run sync code in context of the async fastapi service serving the requests.
Without - the request would block and the service could not serve the request.

test_aiopenapi3_pagination - aiopenapi3/asyncio
test_sync_pagination - aiopenapi3/sync
test_openapi3_pagination_to_thread - openapi3/sync

test_openapi3_pagination_async  - openapi3/asyncio

First three - working fine, last which is supposed to be as close a possible to your MRE does not run a single request due to missing async defs.

**Comment by xloem** [comment]
This is so confusing. I found this and thought openapi3 could do async. @smurfix can you acknowledge that typing "async" was a mistake? Should this issue be closed as trolling?
