### ISSUE TITLE
SpecError when the result is an array

### ISSUE THREAD

**Issue by smurfix** [Dorthu/openapi3#73]
```
openapi3.errors.SpecError: Expected paths./phone/batch_locations.post.responses.201.content.application/json.examples.response.value to be one of [Reference,<class 'dict'>,<class 'str'>], got <class 'list'>
```

The attached file is a reduced version of the spec that exhibits the problem, available from https://marketplace.zoom.us/docs/page-data/api-reference/phone/methods/page-data.json (you need to access `R.result.pageContext.OAS.spec`, then add an `email` field to the `contact` object, duh) where I found the problem.

[phone.json.txt](https://github.com/Dorthu/openapi3/files/8187138/phone.json.txt)

**Comment by smurfix** [comment]
This might be a stupid question, in which case I'd like to apologize in advance, but … is there a reason why you are not using the jsonschema package for this?

**Comment by Dorthu** [comment]
>  is there a reason why you are not using the jsonschema package for this

Admittedly, no.   I'm currently evaluating #69, which reimplements a lot of the core logic here using pydantic (a full usable fork which that branch is based off of is [here](https://github.com/commonism/aiopenapi3)), but that also does not use the jsonschema package.  I'll look into it, as that could simplify a lot.

**Comment by Dorthu** [comment]
Looks like the problem here is that [the OpenAPI standard](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#example-object) defines ax Example type's `value` as "any" type, but this library [only approximates that behavior](https://github.com/Dorthu/openapi3/blob/0e02198948258b69e666f53aa2b22fcf4da62f97/openapi3/example.py#L20).
